exports.pupil = require("./pupil.js")
exports.book = require("./book.js")
exports.kanon = require("./kanon.js")
exports.pupils = require("./pupils.js")
exports.used = require("./used.js")
exports.render = require("./render.js")
